### ISSUE TITLE
No error on insufficient quota

### ISSUE THREAD

**Issue by rwunsch** [jjbankert/hass_chatgpt#9]
I am receiving this response from the API, but in the logs and in the automations I am getting and "unknown error" , or something with "Key error: ["choices"] ...

The response is:
{'error': {'message': 'You exceeded your current quota, please check your plan and billing details.', 'type': 'insufficient_quota', 'param': None, 'code': None}}

**Comment by rwunsch** [comment]
Hi @jjbankert ,

thanks for creating this HA-extension!!
Iit is still simple - but could grow into something very useful! :) 

I think there could be some extra logging, and some checks on the inputs, such as the OpenAI models, or for the valid length of the key etc.
My programming skills (especially in python ) are limited, and with 3 kids I do not have the time any longer to test and debug - at least no more that executing some experiments with HA to improve the existing automations, to make things simpler or better.
I guess AI will be coming massively into HA, as this is a filed where it could be massivley useful.
There might be even a local version running on something like the Google-Coral USB stick, which I already use for Frigate.

I am using this extension to be used with "[alexa actions](https://github.com/keatontaylor/alexa-actions)" (by @keatontaylor ).
I will be using this to customize the questions (and answers) for the actions (using NodeRed) - to not hear the same every time - and to have the smart-home to get a little more "soul".

I would also like to be able to converse with chatCPT - but the "alexa actions" does not yet provide the access to the whole asked question (so the response to the initial question, eg. "What would you like to know?") .
But I think it is in the making in the new versions with the "StringResponseHandler" ( or so I assume) ... which could provide a similar experience talking to chatGPT as talking to Alexa today (and I assume talking to chatGPT naturally could be very interesting :) ).

Thanks again for your work!

**Comment by rwunsch** [comment]
I think checking on the openAI-API errors, and catching them is a good idea! :) 
Link: https://platform.openai.com/docs/guides/error-codes/api-errors

However, the JSON did not provide the error-code - only the error-type ... and the type "insufficient_quota" is not even mentioned in the openAI documentation (I guess every company has a documentation issue :) ).

So I think we could catch each response, where the first key in the JSON response is either "error" or "warn" (supposing this exists as well), and output the response as "error" or "warn".

I am not sure how to test for that in Python.
I think something like that would be sufficient as a starting point:

```
... 
if "error" in response:
  _LOGGER.error('chatgpt - ERROR in API response: %s', response.json() )
elif "warn" in response:
  _LOGGER.warn('chatgpt - WARN in API response: %s', response.json() )
...
```
I am adding a PR to add the code above. (Without adding the other logger, so we have 2 separate PRs).
OK?

**Comment by jjbankert** [comment]
I'm discontinuing the project because my personal use-cases are now covered by the latest Home Assistant release. See the README for my suggested migration option.
